### ISSUE TITLE
The whole words in BERT pre-trained embedding

### ISSUE THREAD

**Issue by Yu-0025** [liangzrtvjivo/GRM#2]
Hi~ I'm not entirely clear on how this step functions. In the case of word2vec, it involves downloading a word embedding file and converting it into a text file. The format of this text file is 'word + embedding.' 

However, I'm a bit uncertain about where the complete vocabulary for BERT's word vector model is sourced from. Could you please explain how this is done?"

Thank you!🌹🌹

**Comment by liangzrtvjivo** [comment]
Thanks for your interest in our work!

It's well known that BERT has its own vocab for tokenizer and the token in this vocab has its own corresponding initial embedding. You can get them through "bert.embeddings.word_embeddings.weight" after loading a BERT model.
We only use the whole words for model training, about 22501 words.

We'll release these preprocessed files to Google Drive including the BERT one in the near future so you can download them directly!
