### ISSUE TITLE
Reproduction code not available

### ISSUE THREAD

**Issue by KUNAL-KAMALKISHOR-BHOSIKAR** [liangzrtvjivo/GRM#3]
Hi, 
Will you please release the code to reproduce the results?
I believe the `reproduce_w2v.sh` and  `reproduce_bert.sh` files mentioned in the 'Reproduction' section are missing.

Thank you for this fantastic work!!!

**Comment by liangzrtvjivo** [comment]
Thanks for your interest in our work!
Sorry for the missing. I've submitted the corresponding files, which reproduce the results via the intermediate word embeddings.
