### ISSUE TITLE
Reproduction of the POS tagging experiments

### ISSUE THREAD

**Issue by jej127** [liangzrtvjivo/GRM#4]
Hello, I am trying to reproduce the results in Table 3 in the paper, especially for the contextual embedding model (i.e., BERT) part.
However, I realized that the code for POS tagging experiment is not included in the repository.
Can I have the code to reproduce the results?
The code might include preprocessing data, training and evaluating the model.
Thanks for your help.

**Comment by liangzrtvjivo** [comment]
Thank you so much for your attention and support to our work! 
Regarding the code for POS tagging task with BERT as the background model, we have uploaded it to the repository for your usage. 
If you encounter any issues or need further assistance, please feel free to contact us.
